# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f3df56317c76461c0eb99e998b25d429958b69e3f8b58d222e7bfca168215f3e9c60c5f9e3e2e2f978a30c113eb0dea40f63e1682b59a74224563cff8bfa56c

test:
  secret_key_base: e7bd59694710b7d437899fb604270c6fe021dcbcc4fc3f12912b443fd2db520abb12af69efe12599dd0fb2a2389c8e17549bef2ca1312aea1373c429ac287a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
